# recon_wp/utils/report.py
"""Report generation utilities for scan results."""

import json
from dataclasses import dataclass, field
from datetime import datetime
from pathlib import Path

from core.finding import Finding


@dataclass
class Report:
    """Aggregated scan report with metadata."""

    target: str
    domain: str
    started_at: datetime = field(default_factory=datetime.utcnow)
    completed_at: datetime = field(default_factory=datetime.utcnow)
    findings: list[Finding] = field(default_factory=list)
    modules_run: list[str] = field(default_factory=list)
    errors: list[str] = field(default_factory=list)

    def get_summary(self) -> dict:
        """Get severity breakdown of findings."""
        summary = {"total": len(self.findings)}
        for sev in ["critical", "high", "medium", "low", "info"]:
            summary[sev] = len([f for f in self.findings if f.severity == sev])
        return summary

    def get_findings_by_severity(self, severity: str) -> list[Finding]:
        """Filter findings by severity."""
        return [f for f in self.findings if f.severity == severity]

    def to_dict(self) -> dict:
        """Serialize report to dictionary."""
        return {
            "target": self.target,
            "domain": self.domain,
            "started_at": self.started_at.isoformat(),
            "completed_at": self.completed_at.isoformat(),
            "duration_seconds": (self.completed_at - self.started_at).total_seconds(),
            "summary": self.get_summary(),
            "modules_run": self.modules_run,
            "errors": self.errors,
            "findings": [f.to_dict() for f in self.findings],
        }


class JsonFormatter:
    """Format report as JSON."""

    @staticmethod
    def format(report: Report, indent: int = 2) -> str:
        """Format report to JSON string."""
        return json.dumps(report.to_dict(), indent=indent, default=str)

    @staticmethod
    def save(report: Report, path: Path) -> None:
        """Save report as JSON file."""
        path.parent.mkdir(parents=True, exist_ok=True)
        with open(path, "w", encoding="utf-8") as f:
            f.write(JsonFormatter.format(report))


class MarkdownFormatter:
    """Format report as Markdown."""

    @staticmethod
    def format(report: Report) -> str:
        """Format report to Markdown string."""
        lines = []

        lines.append(f"# Reconnaissance Report: {report.domain}\n")
        lines.append(f"**Target:** {report.target}\n")
        lines.append(
            f"**Scan Date:** {report.completed_at.strftime('%Y-%m-%d %H:%M:%S UTC')}\n"
        )
        lines.append(
            f"**Duration:** {(report.completed_at - report.started_at).total_seconds():.1f}s\n"
        )

        summary = report.get_summary()
        lines.append("\n## Summary\n")
        lines.append("| Severity | Count |")
        lines.append("|----------|-------|")
        for sev in ["critical", "high", "medium", "low", "info"]:
            count = summary.get(sev, 0)
            emoji = {
                "critical": "💥",
                "high": "🔴",
                "medium": "🟠",
                "low": "🟡",
                "info": "ℹ️",
            }.get(sev, "")
            lines.append(f"| {emoji} {sev.capitalize()} | {count} |")

        lines.append(f"\n**Total Findings:** {summary['total']}\n")

        if report.modules_run:
            lines.append("\n## Modules Run\n")
            for mod in report.modules_run:
                lines.append(f"- {mod}")

        critical_high = report.get_findings_by_severity(
            "critical"
        ) + report.get_findings_by_severity("high")
        if critical_high:
            lines.append("\n## Critical & High Findings\n")
            for f in critical_high:
                lines.append(MarkdownFormatter._format_finding(f))

        medium_low = report.get_findings_by_severity(
            "medium"
        ) + report.get_findings_by_severity("low")
        if medium_low:
            lines.append("\n## Medium & Low Findings\n")
            for f in medium_low:
                lines.append(MarkdownFormatter._format_finding(f))

        info = report.get_findings_by_severity("info")
        if info:
            lines.append("\n## Informational\n")
            for f in info:
                lines.append(MarkdownFormatter._format_finding(f))

        if report.errors:
            lines.append("\n## Errors\n")
            for err in report.errors:
                lines.append(f"- {err}\n")

        lines.append("\n---\n")
        lines.append("*Report generated by WordPress Reconnaissance Tool*\n")

        return "\n".join(lines)

    @staticmethod
    def _format_finding(f: Finding) -> str:
        """Format a single finding as Markdown."""
        badge = {
            "critical": "![critical](https://img.shields.io/badge/-critical-red)",
            "high": "![high](https://img.shields.io/badge/-high-orange)",
            "medium": "![medium](https://img.shields.io/badge/-medium-yellow)",
            "low": "![low](https://img.shields.io/badge/-low-blue)",
            "info": "![info](https://img.shields.io/badge/-info-gray)",
        }.get(f.severity, "")

        lines = [f"\n### {f.title} {badge}\n"]
        lines.append(f"**Module:** {f.module} | **Step:** {f.step}\n")
        lines.append(f"\n{f.description}\n")
        if f.evidence:
            lines.append(f"\n**Evidence:**\n```\n{f.evidence}\n```\n")
        if f.recommendation:
            lines.append(f"\n**Recommendation:** {f.recommendation}\n")
        return "".join(lines)

    @staticmethod
    def save(report: Report, path: Path) -> None:
        """Save report as Markdown file."""
        path.parent.mkdir(parents=True, exist_ok=True)
        with open(path, "w", encoding="utf-8") as f:
            f.write(MarkdownFormatter.format(report))


class SarifFormatter:
    """Format report as SARIF 2.1.0 for CI/CD integration."""

    SCHEMA = "https://raw.githubusercontent.com/oasis-tcs/sarif-spec/v2.1.0/utilities/sarif_schema.json"
    SARIF_VERSION = "2.1.0"

    @classmethod
    def format(cls, report: Report) -> str:
        """Format report to SARIF JSON string."""
        doc = cls._build_document(report)
        return json.dumps(doc, indent=2, default=str)

    @classmethod
    def save(cls, report: Report, path: Path) -> None:
        """Save report as SARIF JSON file."""
        path.parent.mkdir(parents=True, exist_ok=True)
        with open(path, "w", encoding="utf-8") as f:
            f.write(cls.format(report))

    @classmethod
    def _build_document(cls, report: Report) -> dict:
        rules: dict[str, dict] = {}
        results = []

        for finding in report.findings:
            rule_id = f"{finding.module}/{finding.step}"
            if rule_id not in rules:
                rules[rule_id] = {
                    "id": rule_id,
                    "shortDescription": {"text": finding.title},
                    "fullDescription": {"text": finding.description},
                    "defaultConfiguration": {"level": cls._sarif_level(finding.severity)},
                    "properties": {"severity": finding.severity},
                }

            results.append(finding.to_sarif())

        return {
            "$schema": cls.SCHEMA,
            "version": cls.SARIF_VERSION,
            "runs": [
                {
                    "tool": {
                        "driver": {
                            "name": "wp-recon-tool",
                            "version": "1.0.0",
                            "rules": list(rules.values()),
                        }
                    },
                    "results": results,
                    "invocations": [
                        {
                            "startTimeUtc": report.started_at.isoformat(),
                            "endTimeUtc": report.completed_at.isoformat(),
                            "executionSuccessful": len(report.errors) == 0,
                        }
                    ],
                    "properties": {
                        "target": report.target,
                        "domain": report.domain,
                        "modules_run": report.modules_run,
                        "errors": report.errors,
                    },
                }
            ],
        }

    @staticmethod
    def _sarif_level(severity: str) -> str:
        return {
            "critical": "error",
            "high": "error",
            "medium": "warning",
            "low": "note",
            "info": "none",
        }.get(severity, "none")


def generate_report_filename(domain: str, timestamp: datetime) -> str:
    """Generate a base filename for the report (without extension)."""
    ts = timestamp.strftime("%Y%m%d_%H%M%S")
    safe_domain = domain.replace(".", "_").replace(":", "_")
    return f"recon_{safe_domain}_{ts}"
