# recon_wp/utils/report.py
"""Report generation utilities for scan results."""

import json
import math
from dataclasses import dataclass, field
from datetime import datetime
from pathlib import Path

from core.finding import Finding, SARIF_LEVEL_MAP


@dataclass
class Report:
    """Aggregated scan report with metadata."""

    target: str
    domain: str
    started_at: datetime = field(default_factory=datetime.utcnow)
    completed_at: datetime = field(default_factory=datetime.utcnow)
    findings: list[Finding] = field(default_factory=list)
    modules_run: list[str] = field(default_factory=list)
    errors: list[str] = field(default_factory=list)

    def get_summary(self) -> dict:
        """Get severity breakdown of findings."""
        summary = {"total": len(self.findings)}
        for sev in ["critical", "high", "medium", "low", "info"]:
            summary[sev] = len([f for f in self.findings if f.severity == sev])
        return summary

    def get_findings_by_severity(self, severity: str) -> list[Finding]:
        """Filter findings by severity."""
        return [f for f in self.findings if f.severity == severity]

    def to_dict(self) -> dict:
        """Serialize report to dictionary."""
        return {
            "target": self.target,
            "domain": self.domain,
            "started_at": self.started_at.isoformat(),
            "completed_at": self.completed_at.isoformat(),
            "duration_seconds": (self.completed_at - self.started_at).total_seconds(),
            "summary": self.get_summary(),
            "modules_run": self.modules_run,
            "errors": self.errors,
            "findings": [f.to_dict() for f in self.findings],
        }


class JsonFormatter:
    """Format report as JSON."""

    @staticmethod
    def format(report: Report, indent: int = 2) -> str:
        """Format report to JSON string."""
        return json.dumps(report.to_dict(), indent=indent, default=str)

    @staticmethod
    def save(report: Report, path: Path) -> None:
        """Save report as JSON file."""
        path.parent.mkdir(parents=True, exist_ok=True)
        with open(path, "w", encoding="utf-8") as f:
            f.write(JsonFormatter.format(report))


class MarkdownFormatter:
    """Format report as Markdown."""

    @staticmethod
    def format(report: Report) -> str:
        """Format report to Markdown string."""
        lines = []

        lines.append(f"# Reconnaissance Report: {report.domain}\n")
        lines.append(f"**Target:** {report.target}\n")
        lines.append(
            f"**Scan Date:** {report.completed_at.strftime('%Y-%m-%d %H:%M:%S UTC')}\n"
        )
        lines.append(
            f"**Duration:** {(report.completed_at - report.started_at).total_seconds():.1f}s\n"
        )

        summary = report.get_summary()
        lines.append("\n## Summary\n")
        lines.append("| Severity | Count |")
        lines.append("|----------|-------|")
        for sev in ["critical", "high", "medium", "low", "info"]:
            count = summary.get(sev, 0)
            emoji = {
                "critical": "💥",
                "high": "🔴",
                "medium": "🟠",
                "low": "🟡",
                "info": "ℹ️",
            }.get(sev, "")
            lines.append(f"| {emoji} {sev.capitalize()} | {count} |")

        lines.append(f"\n**Total Findings:** {summary['total']}\n")

        if report.modules_run:
            lines.append("\n## Modules Run\n")
            for mod in report.modules_run:
                lines.append(f"- {mod}")

        critical_high = report.get_findings_by_severity(
            "critical"
        ) + report.get_findings_by_severity("high")
        if critical_high:
            lines.append("\n## Critical & High Findings\n")
            for f in critical_high:
                lines.append(MarkdownFormatter._format_finding(f))

        medium_low = report.get_findings_by_severity(
            "medium"
        ) + report.get_findings_by_severity("low")
        if medium_low:
            lines.append("\n## Medium & Low Findings\n")
            for f in medium_low:
                lines.append(MarkdownFormatter._format_finding(f))

        info = report.get_findings_by_severity("info")
        if info:
            lines.append("\n## Informational\n")
            for f in info:
                lines.append(MarkdownFormatter._format_finding(f))

        if report.errors:
            lines.append("\n## Errors\n")
            for err in report.errors:
                lines.append(f"- {err}\n")

        lines.append("\n---\n")
        lines.append("*Report generated by WordPress Reconnaissance Tool*\n")

        return "\n".join(lines)

    @staticmethod
    def _format_finding(f: Finding) -> str:
        """Format a single finding as Markdown."""
        badge = {
            "critical": "![critical](https://img.shields.io/badge/-critical-red)",
            "high": "![high](https://img.shields.io/badge/-high-orange)",
            "medium": "![medium](https://img.shields.io/badge/-medium-yellow)",
            "low": "![low](https://img.shields.io/badge/-low-blue)",
            "info": "![info](https://img.shields.io/badge/-info-gray)",
        }.get(f.severity, "")

        lines = [f"\n### {f.title} {badge}\n"]
        lines.append(f"**Module:** {f.module} | **Step:** {f.step}\n")
        lines.append(f"\n{f.description}\n")
        if f.evidence:
            lines.append(f"\n**Evidence:**\n```\n{f.evidence}\n```\n")
        if f.recommendation:
            lines.append(f"\n**Recommendation:** {f.recommendation}\n")
        return "".join(lines)

    @staticmethod
    def save(report: Report, path: Path) -> None:
        """Save report as Markdown file."""
        path.parent.mkdir(parents=True, exist_ok=True)
        with open(path, "w", encoding="utf-8") as f:
            f.write(MarkdownFormatter.format(report))


class SarifFormatter:
    """Format report as SARIF 2.1.0 for CI/CD integration."""

    SCHEMA = "https://docs.oasis-open.org/sarif/sarif/v2.1.0/errata01/os/schemas/sarif-schema-2.1.0.json"
    SARIF_VERSION = "2.1.0"

    @classmethod
    def format(cls, report: Report) -> str:
        """Format report to SARIF JSON string."""
        doc = cls._build_document(report)
        return json.dumps(doc, indent=2, default=str)

    @classmethod
    def save(cls, report: Report, path: Path) -> None:
        """Save report as SARIF JSON file."""
        path.parent.mkdir(parents=True, exist_ok=True)
        with open(path, "w", encoding="utf-8") as f:
            f.write(cls.format(report))

    @classmethod
    def _build_document(cls, report: Report) -> dict:
        rules: dict[str, dict] = {}
        results = []

        for finding in report.findings:
            rule_id = f"{finding.module}/{finding.step}"
            if rule_id not in rules:
                rules[rule_id] = {
                    "id": rule_id,
                    "shortDescription": {"text": finding.title},
                    "fullDescription": {"text": finding.description},
                    "defaultConfiguration": {"level": cls._sarif_level(finding.severity)},
                    "properties": {"severity": finding.severity},
                }

            results.append(finding.to_sarif())

        return {
            "$schema": cls.SCHEMA,
            "version": cls.SARIF_VERSION,
            "runs": [
                {
                    "tool": {
                        "driver": {
                            "name": "wp-recon-tool",
                            "version": "1.0.0",
                            "rules": list(rules.values()),
                        }
                    },
                    "results": results,
                    "invocations": [
                        {
                            "startTimeUtc": report.started_at.isoformat(),
                            "endTimeUtc": report.completed_at.isoformat(),
                            "executionSuccessful": len(report.errors) == 0,
                        }
                    ],
                    "properties": {
                        "target": report.target,
                        "domain": report.domain,
                        "modules_run": report.modules_run,
                        "errors": report.errors,
                    },
                }
            ],
        }

    @staticmethod
    def _sarif_level(severity: str) -> str:
        return SARIF_LEVEL_MAP.get(severity, "none")


class HtmlFormatter:
    """Format report as a self-contained HTML dashboard page."""

    SEVERITY_ORDER = ["critical", "high", "medium", "low", "info"]

    SEVERITY_COLORS: dict[str, tuple[str, str]] = {
        "critical": ("#e63946", "#4d194d"),
        "high": ("#e76f51", "#3e1f47"),
        "medium": ("#e9c46a", "#312244"),
        "low": ("#457b9d", "#272640"),
        "info": ("#6c757d", "#212f45"),
    }

    _SEVERITY_ACCENT = {
        "critical": "#e63946",
        "high": "#e76f51",
        "medium": "#e9c46a",
        "low": "#457b9d",
        "info": "#6c757d",
    }

    _CSS = """\
:root {
  --stormy-teal: #006466ff;
  --dark-teal: #065a60ff;
  --dark-teal-2: #0b525bff;
  --dark-teal-3: #144552ff;
  --charcoal-blue: #1b3a4bff;
  --deep-space-blue: #212f45ff;
  --space-indigo: #272640ff;
  --midnight-violet: #312244ff;
  --midnight-violet-2: #3e1f47ff;
  --deep-purple: #4d194dff;
  --severity-critical: #e63946;
  --severity-high: #e76f51;
  --severity-medium: #e9c46a;
  --severity-low: #457b9d;
  --severity-info: #6c757d;
  --bg-page: #1a1a2e;
  --bg-card: #212f45;
  --bg-card-alt: #272640;
  --bg-card-hover: #2a2f4a;
  --border-color: #312244;
  --border-light: #3e1f47;
  --text-primary: #e9ecef;
  --text-secondary: #8892a8;
  --text-muted: #6c757d;
  --health-good: #2d6a4f;
  --health-fair: #e9c46a;
  --health-poor: #e63946;
}
*, *::before, *::after { box-sizing: border-box; margin: 0; padding: 0; }
body {
  font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, "Helvetica Neue", Arial, sans-serif;
  background: var(--bg-page); color: var(--text-primary); line-height: 1.6; padding: 24px;
}
.container { max-width: 1024px; margin: 0 auto; }

/* Header */
.header {
  background: linear-gradient(135deg, var(--deep-space-blue), var(--space-indigo), var(--midnight-violet));
  padding: 32px; border-radius: 12px; margin-bottom: 24px;
  display: flex; flex-direction: column; gap: 8px;
}
.header-top { display: flex; justify-content: space-between; align-items: center; }
.header-label { font-size: 0.82rem; text-transform: uppercase; letter-spacing: 1.5px; color: var(--text-secondary); }
.header h1 { font-size: 1.5rem; font-weight: 700; margin: 0; }
.header-meta { display: flex; flex-wrap: wrap; gap: 20px; font-size: 0.88rem; color: var(--text-secondary); }

/* Health score badge */
.health-badge {
  display: inline-flex; align-items: center; gap: 6px;
  padding: 5px 14px; border-radius: 20px;
  font-size: 0.82rem; font-weight: 700;
}
.health-badge.good { background: var(--health-good); color: #fff; }
.health-badge.fair { background: var(--health-fair); color: #1a1a2e; }
.health-badge.poor { background: var(--health-poor); color: #fff; }

/* Dashboard cards */
.dashboard { display: grid; grid-template-columns: repeat(5, 1fr); gap: 12px; margin-bottom: 24px; }
.card {
  background: var(--bg-card); border-radius: 10px; padding: 20px;
  text-align: center; border-top: 3px solid transparent;
  box-shadow: 0 2px 6px rgba(0,0,0,0.15); transition: transform 0.15s, box-shadow 0.15s;
}
.card:hover { transform: translateY(-2px); box-shadow: 0 4px 12px rgba(0,0,0,0.25); }
.card-critical { border-top-color: var(--severity-critical); }
.card-high { border-top-color: var(--severity-high); }
.card-medium { border-top-color: var(--severity-medium); }
.card-low { border-top-color: var(--severity-low); }
.card-info { border-top-color: var(--severity-info); }
.card-count { font-size: 2rem; font-weight: 700; line-height: 1.2; }
.card-critical .card-count { color: var(--severity-critical); }
.card-high .card-count { color: var(--severity-high); }
.card-medium .card-count { color: var(--severity-medium); }
.card-low .card-count { color: var(--severity-low); }
.card-info .card-count { color: var(--severity-info); }
.card-label { font-size: 0.72rem; text-transform: uppercase; letter-spacing: 1.2px; color: var(--text-secondary); margin-top: 4px; }

/* Summary row: donut + scan info */
.summary-row { display: grid; grid-template-columns: 1fr 1fr; gap: 16px; margin-bottom: 24px; }
.section {
  background: var(--bg-card); border-radius: 10px; padding: 24px;
  box-shadow: 0 2px 6px rgba(0,0,0,0.15);
}
.section h2 {
  font-size: 0.85rem; text-transform: uppercase; letter-spacing: 1.2px;
  margin-bottom: 16px; padding-bottom: 10px;
  border-bottom: 1px solid var(--border-light); color: var(--text-secondary);
}
.donut-section { display: flex; flex-direction: column; align-items: center; }
.donut-legend { display: flex; flex-wrap: wrap; gap: 10px; justify-content: center; margin-top: 12px; }
.legend-item { display: flex; align-items: center; gap: 5px; font-size: 0.78rem; color: var(--text-primary); }
.legend-dot { width: 8px; height: 8px; border-radius: 50%; flex-shrink: 0; }

/* Scan info */
.info-grid { display: grid; grid-template-columns: 1fr 1fr; gap: 12px; }
.info-item { padding: 10px 12px; background: var(--bg-card-alt); border-radius: 8px; }
.info-label { display: block; font-size: 0.72rem; text-transform: uppercase; letter-spacing: 0.8px; color: var(--text-muted); margin-bottom: 4px; }
.info-value { font-size: 0.9rem; color: var(--text-primary); }
.info-modules { grid-column: 1 / -1; }
.info-modules .module-list { display: flex; flex-wrap: wrap; gap: 6px; margin-top: 4px; }
.module-tag {
  display: inline-block; padding: 2px 10px; border-radius: 4px;
  background: var(--space-indigo); font-size: 0.78rem; color: var(--text-primary);
}

/* Findings */
.findings-group { margin-bottom: 24px; }
.findings-group details { background: var(--bg-card); border-radius: 10px; overflow: hidden; box-shadow: 0 2px 6px rgba(0,0,0,0.15); }
.findings-group summary {
  display: flex; align-items: center; justify-content: space-between;
  padding: 16px 24px; cursor: pointer; list-style: none; user-select: none;
  font-size: 0.85rem; text-transform: uppercase; letter-spacing: 1.2px; color: var(--text-secondary);
  transition: background 0.15s;
}
.findings-group summary::-webkit-details-marker { display: none; }
.findings-group summary:hover { background: var(--bg-card-hover); }
.findings-group summary::after {
  content: "\25B6"; font-size: 0.7rem; transition: transform 0.2s; color: var(--text-muted);
}
.findings-group details[open] summary::after { transform: rotate(90deg); }
.findings-group summary .severity-dots { display: flex; gap: 4px; align-items: center; }
.findings-group summary .severity-dots .dot { width: 8px; height: 8px; border-radius: 50%; }
.findings-group .findings-body { padding: 8px 24px 24px; }

/* Finding card */
.finding-card {
  padding: 16px; margin-bottom: 12px; border-radius: 8px;
  border-left: 4px solid transparent; background: var(--bg-card-alt);
  transition: background 0.15s;
}
.finding-card:last-child { margin-bottom: 0; }
.finding-card:hover { background: var(--bg-card-hover); }
.finding-card .fc-top { display: flex; align-items: flex-start; justify-content: space-between; gap: 12px; margin-bottom: 6px; }
.finding-card .fc-title { font-size: 0.95rem; font-weight: 600; color: var(--text-primary); }
.finding-card .fc-mod-step { font-size: 0.78rem; color: var(--text-muted); margin-bottom: 6px; }
.finding-card .fc-desc { font-size: 0.88rem; color: var(--text-primary); margin-bottom: 8px; }
.finding-card .fc-evidence {
  background: #151a2e; border: 1px solid var(--border-color); border-radius: 6px;
  padding: 12px; overflow-x: auto; font-size: 0.82rem; line-height: 1.4;
  margin: 8px 0; white-space: pre-wrap; font-family: "SF Mono", "Cascadia Code", "Fira Code", monospace;
  color: #cdd6f4;
}
.finding-card .fc-rec {
  background: var(--space-indigo); border-radius: 6px; padding: 10px 12px;
  font-size: 0.84rem; margin-top: 8px; color: #b8c0e0;
}
.finding-card .fc-rec strong { color: var(--severity-medium); }

/* Badge */
.badge {
  display: inline-block; padding: 3px 10px; border-radius: 4px;
  font-size: 0.7rem; font-weight: 700; text-transform: uppercase; letter-spacing: 0.5px;
  white-space: nowrap; flex-shrink: 0;
}
.badge-critical { background: #4a1525; color: var(--severity-critical); }
.badge-high { background: #4a1e15; color: var(--severity-high); }
.badge-medium { background: #4a3e15; color: var(--severity-medium); }
.badge-low { background: #152a4a; color: var(--severity-low); }
.badge-info { background: #2a2a2a; color: var(--severity-info); }

/* Errors */
.errors-section { margin-bottom: 24px; }
.errors-section .section { border-left: 3px solid var(--severity-critical); }
.errors-section .section h2 { color: var(--severity-critical); border-bottom-color: #4a1525; }
.errors-section ul { list-style: none; padding: 0; }
.errors-section li {
  padding: 8px 12px; margin-bottom: 4px; border-radius: 6px;
  background: var(--bg-card-alt); color: var(--severity-critical); font-size: 0.88rem;
}

/* Footer */
.footer { text-align: center; font-size: 0.8rem; color: var(--text-muted); padding: 24px 0 12px; }

/* Responsive */
@media (max-width: 768px) {
  .dashboard { grid-template-columns: repeat(2, 1fr); }
  .summary-row { grid-template-columns: 1fr; }
  .info-grid { grid-template-columns: 1fr; }
  .info-modules { grid-column: 1; }
  body { padding: 12px; }
}
@media (max-width: 480px) {
  .dashboard { grid-template-columns: repeat(2, 1fr); gap: 8px; }
  .card { padding: 14px; }
  .card-count { font-size: 1.5rem; }
}

/* Print */
@media print {
  body { background: #fff !important; padding: 10px; color: #000; }
  .header { background: #212f45 !important; -webkit-print-color-adjust: exact; print-color-adjust: exact; }
  .card { break-inside: avoid; box-shadow: none; border: 1px solid #ddd; }
  .badge, .health-badge { -webkit-print-color-adjust: exact; print-color-adjust: exact; }
  .legend-dot, .module-tag, .finding-card .fc-rec { -webkit-print-color-adjust: exact; print-color-adjust: exact; }
  .section { break-inside: avoid; box-shadow: none; border: 1px solid #ddd; }
  .finding-card { break-inside: avoid; }
}
"""

    @staticmethod
    def format(report: Report) -> str:
        return HtmlFormatter._build_html(report)

    @staticmethod
    def save(report: Report, path: Path) -> None:
        path.parent.mkdir(parents=True, exist_ok=True)
        with open(path, "w", encoding="utf-8") as f:
            f.write(HtmlFormatter.format(report))

    @classmethod
    def _build_html(cls, report: Report) -> str:
        summary = report.get_summary()
        duration = (report.completed_at - report.started_at).total_seconds()
        score, score_label, score_color = cls._calculate_health_score(summary)

        return f"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>Reconnaissance Report: {cls._esc(report.domain)}</title>
<style>{cls._CSS}</style>
</head>
<body>
<div class="container">

{cls._render_header(report, score, score_label, score_color)}
{cls._render_dashboard_cards(summary)}
{cls._render_summary_row(report, summary, duration)}
{cls._render_findings(report)}
{cls._render_errors(report)}

<div class="footer">Report generated by WordPress Reconnaissance Tool</div>
</div>
</body>
</html>"""

    @classmethod
    def _render_header(cls, report: Report, score: int, score_label: str, score_color: str) -> str:
        duration = (report.completed_at - report.started_at).total_seconds()
        return f"""<header class="header">
  <div class="header-top">
    <span class="header-label">Reconnaissance Report</span>
    <span class="health-badge {score_label}" style="background:{score_color}">{score}/100 &middot; {score_label}</span>
  </div>
  <h1>{cls._esc(report.domain)}</h1>
  <div class="header-meta">
    <span>Target: {cls._esc(report.target)}</span>
    <span>Date: {report.completed_at.strftime('%Y-%m-%d %H:%M:%S UTC')}</span>
    <span>Duration: {duration:.1f}s</span>
  </div>
</header>"""

    @classmethod
    def _render_dashboard_cards(cls, summary: dict) -> str:
        cards = []
        for sev in cls.SEVERITY_ORDER:
            count = summary.get(sev, 0)
            accent = cls._SEVERITY_ACCENT.get(sev, "#6c757d")
            cards.append(f"""<div class="card card-{sev}">
  <div class="card-count">{count}</div>
  <div class="card-label">{sev.upper()}</div>
</div>""")
        return f'<div class="dashboard">{"".join(cards)}</div>'

    @classmethod
    def _render_summary_row(cls, report: Report, summary: dict, duration: float) -> str:
        total = summary.get("total", 0)
        donut = cls._render_donut_chart(summary)

        modules_html = ""
        if report.modules_run:
            tags = "".join(
                f'<span class="module-tag">{cls._esc(m)}</span>'
                for m in report.modules_run
            )
            modules_html = f"""<div class="info-item info-modules">
  <span class="info-label">Modules Run</span>
  <div class="module-list">{tags}</div>
</div>"""

        return f"""<div class="summary-row">
  <div class="section donut-section">
    <h2>Severity Distribution</h2>
    {donut}
  </div>
  <div class="section">
    <h2>Scan Overview</h2>
    <div class="info-grid">
      {modules_html}
      <div class="info-item">
        <span class="info-label">Duration</span>
        <span class="info-value">{duration:.1f}s</span>
      </div>
      <div class="info-item">
        <span class="info-label">Total Findings</span>
        <span class="info-value">{total}</span>
      </div>
      <div class="info-item">
        <span class="info-label">Errors</span>
        <span class="info-value">{len(report.errors)}</span>
      </div>
      <div class="info-item">
        <span class="info-label">Health Score</span>
        <span class="info-value">{cls._calculate_health_score(summary)[0]}/100</span>
      </div>
    </div>
  </div>
</div>"""

    @classmethod
    def _render_donut_chart(cls, summary: dict) -> str:
        total = summary.get("total", 0)
        if total == 0:
            return '<div style="color:var(--text-muted);font-size:0.9rem;padding:20px;">No findings to display</div>'

        cx, cy = 80, 80
        inner_r = 46
        stroke_w = 18
        circumference = 2 * math.pi * inner_r

        circles = []
        cumulative = 0.0
        colors = cls._SEVERITY_ACCENT

        for sev in cls.SEVERITY_ORDER:
            count = summary.get(sev, 0)
            if count == 0:
                continue
            pct = count / total
            seg_len = circumference * pct
            offset = -cumulative * circumference
            cumulative += pct
            circles.append(
                f'<circle cx="{cx}" cy="{cy}" r="{inner_r}" fill="none" '
                f'stroke="{colors[sev]}" stroke-width="{stroke_w}" '
                f'stroke-dasharray="{seg_len:.1f} {circumference:.1f}" '
                f'stroke-dashoffset="{offset:.1f}" '
                f'transform="rotate(-90 {cx} {cy})" stroke-linecap="butt"/>'
            )

        legend_items = ""
        for sev in cls.SEVERITY_ORDER:
            count = summary.get(sev, 0)
            if count == 0:
                continue
            accent = colors[sev]
            legend_items += (
                f'<span class="legend-item">'
                f'<span class="legend-dot" style="background:{accent}"></span>'
                f'{sev} ({count})</span>'
            )

        return f"""<svg width="160" height="160" viewBox="0 0 160 160" style="display:block;">
  <circle cx="{cx}" cy="{cy}" r="{inner_r}" fill="none" stroke="var(--border-color)" stroke-width="{stroke_w}" opacity="0.5"/>
  {"".join(circles)}
  <circle cx="{cx}" cy="{cy}" r="28" fill="var(--bg-card)"/>
  <text x="{cx}" y="{cy - 4}" text-anchor="middle" fill="var(--text-primary)" font-size="26" font-weight="700" font-family="inherit">{total}</text>
  <text x="{cx}" y="{cy + 16}" text-anchor="middle" fill="var(--text-muted)" font-size="11" font-family="inherit">findings</text>
</svg>
<div class="donut-legend">{legend_items}</div>"""

    @classmethod
    def _render_findings(cls, report: Report) -> str:
        sections = []
        groups = [
            ("critical", "high", "Critical &amp; High Findings", ["critical", "high"], True),
            ("medium", "low", "Medium &amp; Low Findings", ["medium", "low"], False),
            ("info", None, "Informational", ["info"], False),
        ]
        for sev_a, sev_b, title, severities, default_open in groups:
            findings = report.get_findings_by_severity(sev_a)
            if sev_b:
                findings += report.get_findings_by_severity(sev_b)
            if not findings:
                continue
            items = "\n".join(cls._render_finding(f) for f in findings)

            dots = "".join(
                f'<span class="dot" style="background:{cls._SEVERITY_ACCENT[s]}"></span>'
                for s in severities
                if any(f.severity == s for f in findings)
            )

            sections.append(f"""<div class="findings-group">
  <details{" open" if default_open else ""}>
    <summary>
      <span>{title}</span>
      <span class="severity-dots">{dots}</span>
    </summary>
    <div class="findings-body">
      {items}
    </div>
  </details>
</div>""")
        return "\n".join(sections)

    @classmethod
    def _render_finding(cls, f: Finding) -> str:
        rec_html = ""
        if f.recommendation:
            rec_html = f'<div class="fc-rec"><strong>Recommendation:</strong> {cls._esc(f.recommendation)}</div>'
        evidence_html = ""
        if f.evidence:
            evidence_html = f'<div class="fc-evidence">{cls._esc(f.evidence)}</div>'
        return f"""<div class="finding-card" style="border-left-color:{cls._SEVERITY_ACCENT.get(f.severity, '#6c757d')}">
  <div class="fc-top">
    <span class="fc-title">{cls._esc(f.title)}</span>
    <span class="badge badge-{f.severity}">{f.severity.upper()}</span>
  </div>
  <div class="fc-mod-step">{cls._esc(f.module)} / {cls._esc(f.step)}</div>
  <div class="fc-desc">{cls._esc(f.description)}</div>
  {evidence_html}
  {rec_html}
</div>"""

    @classmethod
    def _render_errors(cls, report: Report) -> str:
        if not report.errors:
            return ""
        items = "\n".join(
            f"<li>{cls._esc(e)}</li>" for e in report.errors
        )
        return f"""<div class="errors-section">
  <div class="section">
    <h2>Errors</h2>
    <ul>{items}</ul>
  </div>
</div>"""

    @staticmethod
    def _calculate_health_score(summary: dict) -> tuple[int, str, str]:
        critical = summary.get("critical", 0)
        high = summary.get("high", 0)
        medium = summary.get("medium", 0)
        low = summary.get("low", 0)
        score = max(0, 100 - (critical * 25 + high * 10 + medium * 3 + low * 1))
        if score >= 80:
            return score, "good", "#2d6a4f"
        elif score >= 50:
            return score, "fair", "#e9c46a"
        return score, "poor", "#e63946"

    @staticmethod
    def _esc(s: str) -> str:
        return s.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;").replace('"', "&quot;").replace("'", "&#x27;")


class PdfFormatter:
    """Format report as PDF via WeasyPrint."""

    @classmethod
    def format(cls, report: Report) -> bytes:
        html = HtmlFormatter.format(report)
        try:
            from weasyprint import HTML
        except ImportError:
            raise ImportError(
                "WeasyPrint is required for PDF output. Install it with: "
                "pip install weasyprint   # or: pip install 'wordpress-recon-tool[pdf]'"
            ) from None
        return HTML(string=html).write_pdf()

    @classmethod
    def save(cls, report: Report, path: Path) -> None:
        path.parent.mkdir(parents=True, exist_ok=True)
        with open(path, "wb") as f:
            f.write(cls.format(report))


def generate_report_filename(domain: str, timestamp: datetime) -> str:
    """Generate a base filename for the report (without extension)."""
    ts = timestamp.strftime("%Y%m%d_%H%M%S")
    safe_domain = domain.replace(".", "_").replace(":", "_")
    return f"recon_{safe_domain}_{ts}"
